# Generated by Django 4.0.1 on 2025-03-02 17:09

import audit_fields.fields.userfield
import audit_fields.fields.uuid_auto_field
import audit_fields.models.audit_model_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEngineModel',
            fields=[
                ('created', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('id', audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=250, unique=True)),
                ('sql_query', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('report_main_header', models.CharField(blank=True, max_length=250)),
                ('report_sub_header', models.CharField(blank=True, max_length=250)),
                ('numerical_columns', models.TextField(blank=True, max_length=5000)),
                ('filter_columns', models.TextField(default=None, null=True)),
            ],
        ),
    ]
